default:
  mode: debug
  app:
    rpcPort: 8080
    httpPort: 8090

dbConfig:
  dsn: "root:123456@tcp(127.0.0.1:33060)/test?charset=utf8mb4&parseTime=True&loc=Local"
  maxOpenConn: 20
  maxLifeTime: 1800
  maxIdleConn: 5


sqlConfig:
  - name: userList
    table: users
    sql: "select * from users where user_id>@id"
  - name: deptList
    table: depts
    sql: ""
  - name: addUser
    sql: "insert into users(user_name, user_password) values(@user_name, @user_password)"
    select:
      sql: "SELECT LAST_INSERT_ID() as user_id"
  - name: addUserOrder
    sql: "insert into user_order(user_id) values(@user_id)"

  - name: deleteUser
    sql: "delete from users where user_id=@user_id"
